version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: siip
      POSTGRES_PASSWORD: siip
      POSTGRES_DB: siipdb
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"